const hotels = [
  {
    id: 1,
    name: "Atlantis The Palm",
    type: "Luxury",
    location: "Palm Jumeirah, Dubai",
    rating: 4.9,
    pricePerNight: 18000,
    imageUrl: "https://example.com/atlantis.jpg",
    website: "https://www.atlantis.com/dubai",
    amenities: ["wifi", "gym", "breakfast"],
    description: "Atlantis The Palm is an iconic luxury resort with stunning sea views and unmatched hospitality.",
  },
  {
    id: 2,
    name: "Rove Downtown",
    type: "Budget",
    location: "Downtown Dubai",
    rating: 4.3,
    pricePerNight: 8000,
    imageUrl: "https://example.com/rove.jpg",
    website: "https://www.rovehotels.com",
    amenities: ["wifi", "gym", "breakfast"],
    description: "Rove Downtown is a stylish and affordable hotel close to the Burj Khalifa and Dubai Mall.",
  },
  {
    id: 3,
    name: "Jumeirah Beach Hotel",
    type: "Resort",
    location: "Jumeirah Road, Dubai",
    rating: 4.7,
    pricePerNight: 15000,
    imageUrl: "https://example.com/jumeirah.jpg",
    website: "https://www.jumeirah.com",
    amenities: ["wifi", "gym"],
    description: "Jumeirah Beach Hotel offers a luxurious beachfront experience with world-class amenities.",
  },
  {
    id: 4,
    name: "Premier Inn Dubai International Airport",
    type: "Economy",
    location: "Dubai Airport",
    rating: 4.1,
    pricePerNight: 6000,
    imageUrl: "https://example.com/premierinn.jpg",
    website: "https://mena.premierinn.com",
    amenities: ["wifi", "breakfast"],
    description: "Ideal for short stays, Premier Inn near Dubai Airport offers comfort, convenience, and free shuttle service.",
  },
];